apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-comp
  namespace: deploy
  labels:
    app: testing
spec: 
  replicas: 3
  strategy:
    type: Recreate
    #rollingUpdates:
    #maxSurge: 2
    #maxUnavailable: 0
  selector: 
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing     
    spec:
      containers:
        - name: testing
          image: jenkins:2.60.2
          #image: bitbull/webserver
          ports:
          - containerPort: 80