apiVersion: v1
kind: Pod
metadata:
  name: deploy
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: testing
    image: bitbull/webserver
    imagePullPolicy: IfNotPresent