apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: testing
  labels:
    name: test
spec:
  containers:
    - name: hello
      image: gcr.io/central-academy-298905/myimage:latest
      ports:
        - containerPort: 80 
