

apiVersion: v1
kind: Pod
metadata:
  name: deploy-comp
  labels:
    security: s1
spec:
  containers:
    - name: testing
      image: supergaintkir/animals:bear
  tolerations: 
  - key: "special" 
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"


